import type { Metadata } from "next";
import Link from "next/link";
import { logOut } from "../../../../actions/auth";
import { getUserSession } from "../../../../actions/auth";
import { redirect } from "next/navigation";
import { StreamVideoProvider } from "../../providers/StreamVideoProvider";

export const metadata: Metadata = {
	title: "Activity Dashboard | Sarvagya",
	description: "Generated by create next app",
};

export default async function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { user } = await getUserSession();
	if (!user?.user_metadata.image) { 
		redirect("/instructor/auth/login");
	}
	return (
 <StreamVideoProvider>
				 <main className="w-full min-h-screen">
            	<nav className='w-full px-8 py-4 flex items-center justify-between h-[10vh] border-b-[1px] border-gray-300'>
						<h2 className='font-bold text-2xl'>Sarvagya</h2>
						

                <div className="flex items-center space-x-4 justify-between">
                    <Link href={`/instructor/${user.id}`} className="hover:underline">
								{user.user_metadata.name}</Link>
                    <button className='bg-red-500 text-white px-4 py-2 rounded-md cursor-pointer' onClick={logOut}>
					Log Out
				</button>
                </div>
            </nav>
					{children}
			</main>
			</StreamVideoProvider>
	);
}