import { StreamVideoProvider } from "../providers/StreamVideoProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Calls & Chat | Sarvagya",
	description: "Generated by create next app",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	
    return (
        <StreamVideoProvider>
            {children}
        </StreamVideoProvider>

	);
}